# -*- coding: utf-8 -*-
"""Sammies.pt.2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CAna30Zl2H3UfISVZnKW65nRXk7MZOn2
"""

import pandas as pd
import numpy as np
import warnings
# Suppress all warnings
warnings.filterwarnings("ignore")
#warnings.resetwarnings()

# display entire column and row content
pd.set_option('display.max_columns', None)

# read 2022 demographic data
df = pd.read_excel('2022_FEVS.xlsx', sheet_name='2022_Fevs')

df

# Please select the racial category or categories with which you most closely identify.
race = df['DRNO']
race[race == 'A'] = 'Black or African American'
race[race == 'B'] = 'White'
race[race == 'C'] = 'Asian'
race[race == 'D'] = 'Other Groups'

# Are you of Hispanic, Latino, or Spanish origin?
eth = df['DHISP']
eth[eth == 'A'] = 'Yes'
eth[eth == 'B'] = 'No'

# Are you an individual with a disability?
dis = df['DDIS']
dis[dis == 'A'] = 'Yes'
dis[dis == 'B'] = 'No'

# What is your age group?
age = df['DAGEGRP']
age[age == 'A'] = 'Under 40'
age[age == 'B'] = '40 or Older'

# What is your supervisory status?
sup = df['DSUPER']
sup[sup == 'A'] = 'Non-Supervisor/Team Leader'
sup[sup == 'B'] = 'Supervisor/Manager/Executive'

# How long have you been with the Federal Government (excluding military service)?
service_yrs = df['DFEDTEN']
service_yrs[service_yrs == 'A'] = 'Ten years or fewer'
service_yrs[service_yrs == 'B'] = 'Eleven to 20 years'
service_yrs[service_yrs == 'C'] = 'More than 20 years'

# Are you:
sex = df['DSEX']
sex[sex == 'A'] = 'Male'
sex[sex == 'B'] = 'Female'

# What is your US military service status?
military = df['DMIL']
military[military == 'A'] = 'Military Service'
military[military == 'B'] = 'No Prior Military Service'

# Are you considering leaving your organization within the next year, and if so, why?
leaving = df['DLEAVING']
leaving[leaving == 'A'] = 'No'
leaving[leaving == 'B'] = 'Yes, other'
leaving[leaving == 'C'] = 'Yes, to take another job within the Federal Government'
leaving[leaving == 'D'] = 'Yes, to take another job outside the Federal Government'

def map_agency_codes(agency_column, code_mapping):
    for code, description in code_mapping.items():
        agency_column[agency_column == code] = description

    return agency_column

code_mapping = {
    'AF': 'United States Department of the Air Force',
    'AG': 'Department of Agriculture',
    'AM': 'U.S. Agency for International Development',
    'AR': 'United States Department of the Army',
    'CM': 'Department of Commerce',
    'CU': 'National Credit Union Administration',
    'DD': 'OSD, Joint Staff, Defense Agencies, and Field Activities',
    'DJ': 'Department of Justice',
    'DL': 'Department of Labor',
    'DN': 'Department of Energy',
    'DR': 'Federal Energy Regulatory Commission',
    'ED': 'Department of Education',
    'EE': 'Equal Employment Opportunity Commission',
    'EP': 'Environmental Protection Agency',
    'FT': 'Federal Trade Commission',
    'GS': 'General Services Administration',
    'HE': 'Department of Health and Human Services',
    'HS': 'Department of Homeland Security',
    'HU': 'Department of Housing and Urban Development',
    'IN': 'Department of the Interior',
    'NF': 'National Science Foundation',
    'NQ': 'National Archives and Records Administration',
    'NU': 'Nuclear Regulatory Commission',
    'NV': 'United States Department of the Navy',
    'OM': 'Office of Personnel Management',
    'SB': 'Small Business Administration',
    'ST': 'Department of State',
    'SZ': 'Social Security Administration',
    'TD': 'Department of Transportation',
    'TR': 'Department of the Treasury',
    'XX': 'All Other Agencies',
}

df['Agency'] = map_agency_codes(df['Agency'], code_mapping)

df

# converting to xlsx files
df.to_excel('fevsData_2022.xlsx', index=False)

# display the percentages of each column values
for column in df.columns:
    percentages = df[column].value_counts(normalize=True) * 100
    print(f"\nColumn: {column}")
    print(percentages)